name: TypedTags
description: Plugin for typing in tags when adding or editing a node

author: Israel Segundo/Felipe Garcia Hernandez
authorEmail: israel.segundo@gmail.com, felgarciah@gmail.com
authorUrl: 
